workspace:
  base: /srv/src/go
  path: src/github.com/magneticio/vamp-gateway-agent

pipeline:
  build:
    image: iamtew/vamp-buildserver:dev
    commands:
      - ./build.sh --make

  dockerize:
    image: docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd target/docker
      - docker build --tag iamtew/vamp-gateway-agent:dev .

