language: go
sudo: false

go:
  - 1.5.1

script: bash build.sh --make

after_success: |
  if [ -n "$GITHUB_API_KEY" ] && [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ $TRAVIS_BRANCH == "master" ] && [ ! -n "$TRAVIS_TAG" ]; then

    VERSION=0.8.0

    TMP_DIR=/tmp/vamp
    GIT_COMMIT=`git rev-parse --short HEAD`

    git clone -b ${VERSION} https://github.com/magneticio/vamp-gateway-agent.git $TMP_DIR > /dev/null 2>&1

    if [ ! -d "$TMP_DIR" ]; then
      mkdir -p $TMP_DIR
    fi

    rm -fR $TMP_DIR/* > /dev/null 2>&1
    mv -f target/docker/* $TMP_DIR/.
    cp LICENSE $TMP_DIR/.
    cp README.md $TMP_DIR/.
    cd $TMP_DIR

    if [ ! -d ".git" ]; then
      git init
      git checkout -b ${VERSION}
    fi

    git add . > /dev/null 2>&1
    git -c user.name='travis' -c user.email='travis' commit -m "build $GIT_COMMIT"
    git push -f -q https://$GITHUB_API_KEY@github.com/magneticio/vamp-gateway-agent.git ${VERSION} > /dev/null 2>&1

    cd $TRAVIS_BUILD_DIR
  fi

env:
  matrix:
    secure: GMLLA4QspoFvkjGwVg0VTHuqnSJRqI3RMTkDtLLvdZxGgmoytidnUbewjmuV5v9rfGWtjg3ZKXN1aY5QUNHXNTeOixJ/6VeD4c8vIyenlmFMwvIHYZ+WD6q+cscJp59ocjrJgS/qqcpj2MvY0GzOOn1FKkV5g9+WZEtEPe4+1TudHpODY36R64Hst2hd+N+OXiWSUeSDF+Rfbqf6ZuKVuny6FJF8PwD5Zj3+K9gFREC0jgZJwGM+74v++OXGGIthrPZzJ3aeW2vWKl2+ASgfxGV1Iw3KeRCFPCBH6rJbVnJ0k7y2YyBZeiDeftCxwke65leinTpkxorxqjWKgk5HjO4cKbljLne8CkI3TGaQHrvz1uk7yOwxM0E1wbvDj4+RbvgsvoEWNZL7hHDY2xL3GvHZOXKUPuW5tmZcsr/EUzw2B4V5j3Sv/rYncak76u8uufBumP+TJ5mPDGekzUt4CRIXVe+DlsIpVLKtfl0NwYNpVxMpYJWoBPYeSzR4C3Bv74gE2nCHk4Hsh9a71uEDtW/3ykhuvS7MymD4eIzI8usN5+rfcigM/sMVYpMrFerOvCKUQe1R7V5PeUzLRZ4XZ/ohMT06ypd/CcR6rM1buHp5oKcrCdGXJYVnUtwFDpXwFiXmAnPwrjjU16RLWMEsOSUUIXs/LQlHDNBp46vYiiA=
